SELECT 
	MONTH(TGL) Bulan,
	SUM(DEBET) JDebit,
	SUM(KREDIT) JKredit
FROM jurnal2019
GROUP BY MONTH(TGL);


SELECT 
	KODE_AKUN,
	NAMA_AKUN,
	SUM(DEBET) AS JDEBET,
	SUM(KREDIT) AS JKREDIT
FROM jurnal2019
	JOIN bagan_akun
	ON jurnal2019.kode_akun = bagan_akun.kode
WHERE MONTH(tgl) = 1
GROUP BY KODE_AKUN;

